#!/bin/bash
# http://www.tacc.utexas.edu/user-services/user-guides/stampede-user-guide
#SBATCH -J 1P10p05
#SBATCH -o run.o%j              # Output and error file name (%j expands to jobID)
#SBATCH -e run.e%j              # Output and error file name (%j expands to jobID)
#SBATCH -p test                 # Queue name
#SBATCH -N 1                    # Total number of nodes requested (48 cores/node)
#SBATCH -n 32                   # Total number of mpi tasks requested
#SBATCH -t 00:25:00             # Run time (hh:mm:ss)
#SBATCH --mem-per-cpu=3000      # Memory pool for all cores
#SBATCH --mail-type=END         # Type of email notification- BEGIN, END, FAIL, ALL
#SBATCH --contiguous
#SBATCH --mail-user=blemaire@g.harvard.edu # Email to which notifications will be sent

module load intel/17.0.4-fasrc01 openmpi/3.1.1-fasrc01 lammps/22Aug18-fasrc01
srun --cpu_bind=cores --mpi=pmi2 -n $SLURM_NTASKS lmp -in lammps_input_NVT6_w1H2O_s5.in > log_file