#!/bin/bash
# http://www.tacc.utexas.edu/user-services/user-guides/stampede-user-guide
#SBATCH -J 1P10p05
#SBATCH -o run.o%j              # Output and error file name (%j expands to jobID)
#SBATCH -e run.e%j              # Output and error file name (%j expands to jobID)
#SBATCH -p skx-normal    # Queue name
#SBATCH -N 1                    # Total number of nodes requested (48 cores/node)
#SBATCH -n 48                   # Total number of mpi tasks requested
#SBATCH -t 00:25:00             # Run time (hh:mm:ss)
#SBATCH -A TG-MSS180011        # <-- Allocation name to charge job against
#SBATCH --mail-type=END         # Type of email notification- BEGIN, END, FAIL, ALL
#SBATCH --mail-user=blemaire@g.harvard.edu # Email to which notifications will be sent

module load intel/17.0.4
module load impi/17.0.3
module load lammps/16Mar18

export OMP_NUM_THREADS=1

ibrun lmp_stampede -in lammps_input_NVT6_w1H2O_s5.in > log_file